###=============================================================================
###=============================================================================
###           C.L.I.E.N.T.E.S                                                ###
###          -----------------                                               ###
###=============================================================================
###=============================================================================
###               Listar
GET http://localhost:5028/api/cliente/listar

###               Buscar
GET http://localhost:5028/api/cliente/buscar/12

###              Cadastrar
POST http://localhost:5028/api/cliente/cadastrar
Content-Type: application/json

{
    "Nome" : "Boris",
    "Telefone" : "998765432",
    "Cpf" : "3192"
}

###              Deletar
DELETE http://localhost:5028/api/cliente/deletar/3

###              Alterar
PUT http://localhost:5028/api/cliente/alterar/3
Content-Type: application/json

{
    "Nome" : "Junior",
    "Telefone" : "998765432"
}

###=============================================================================
###=============================================================================
###      F.U.N.C.I.O.R.A.R.I.O.S                                             ###
###     -------------------------                                            ###
###=============================================================================
###=============================================================================
###              Listar
GET http://localhost:5028/api/funcionario/listar

###              Buscar
GET http://localhost:5028/api/funcionario/buscar/2

###            Cadastrar
POST http://localhost:5028/api/funcionario/cadastrar
Content-Type: application/json

{
    "Nome" : "Marcos",
    "Cargo" : "Luthier",
    "NRegistro" : "27"
}
###             Deletar
DELETE http://localhost:5028/api/funcionario/deletar/7

###             Alterar
PUT http://localhost:5028/api/funcionario/alterar/2
Content-Type: application/json

{
    "Nome" : "Marcos",
    "Cargo" : "Luthier Senior"
}

###=============================================================================
###=============================================================================
###          P.E.D.I.D.O.S                          ↘️               ↙️     ###
###         ---------------                           OrdensDeServicos       ###
###=============================================================================
###=============================================================================

###             Listar 
GET http://localhost:5028/api/ordemservico/listar

###             Buscar
GET http://localhost:5028/api/ordemservico/buscar/1

###            Cadastrar
POST http://localhost:5028/api/ordemservico/cadastrar/
Content-Type: application/json

{
    "DescricaoServico" : "Alinhamento Violao",
    "Instrumento" : "Takamine",
    "Status" : "Finalizado",
    "ClienteId" : "3",
    "FuncionarioId" : "3",
    "ValorEstimado" : 11150.00
}

###            Deletar
DELETE http://localhost:5028/api/ordemservico/deletar/1

###            Alterar
PUT http://localhost:5028/api/ordemservico/alterar/3
Content-Type: application/json

{
    "DescricaoServico" : "Trocar cortiça",
    "Status" : "Finalizado",
    "ValorEstimado" : 750.00
}

###=============================================================================
###=============================================================================
###      F.I.L.T.R.O.S   D.E    P.E.S.Q.U.I.S.A                              ###
###     --------------- -----  -----------------                             ###
###=============================================================================
###=============================================================================
###             Listar ordens de serviço ordenadas por data de criação
GET http://localhost:5028/ordemservico/listar/OrderBy/DateTime/

###             Buscar ordens de serviço por descrições semelhantes
GET http://localhost:5028/ordemservico/buscar/descricao/Trocar%20cortiça

###             Buscar ordens de serviço com status "Em Aberto"
GET http://localhost:5028/ordemservico/status/Em%20Aberto

###             Buscar manutenções concluídas de um cliente específico
GET http://localhost:5028/ordemservico/finalizadas/cliente/3

###             Buscar todas as manutenções de um cliente (finalizadas ou não)
GET http://localhost:5028/ordemservico/todas/cliente/1

###             Buscar ordens de serviço realizadas por um funcionário específico
GET http://localhost:5028/ordemservico/funcionario/3